### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by almet** [BaptisteGelez/squs#2]
Hi,

First, thanks for the work. I love the idea of using the fediverse to replace comments :-) I'm currently using a static site myself, and would like to use squs with it, but I'm left to understand how I should deploy all this and how I should integrate it.

Do you plan on adding some (even scarce) documentation? Thanks!

**Comment by bnjbvr** [comment]
Thanks @BaptisteGelez, I think this is now fixed! See also https://github.com/BaptisteGelez/squs#install-your-instance .

**Comment by almet** [comment]
Yes! Thanks a bunch :-)
